# Generated by Django 2.1.5 on 2022-03-21 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_replies',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
