# Generated by Django 2.1.5 on 2022-03-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeWeek', models.ForeignKey(on_delete=None, to='studenteats.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='deals',
            name='Deal_ID',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Deals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studenteats.Deals'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='admindetails',
            name='restaurantWeek',
            field=models.ForeignKey(on_delete=None, to='studenteats.Restaurant'),
        ),
    ]
