# Generated by Django 2.1.5 on 2022-03-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'restaurants'},
        ),
    ]
