# Generated by Django 2.1.5 on 2022-03-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Prfoile_Picture_Path',
            new_name='Profile_Picture_Path',
        ),
    ]
