# Generated by Django 2.1.5 on 2022-03-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='View',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='Discussion_ID',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Prfoile_Picture_Path',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
