# Generated by Django 2.1.5 on 2022-03-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
