# Generated by Django 2.1.5 on 2022-03-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0002_auto_20220316_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='View',
            new_name='Views',
        ),
    ]
