# Generated by Django 2.1.5 on 2022-03-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0002_auto_20220314_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Deals',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studenteats.Deals'),
        ),
    ]
