# Generated by Django 2.1.5 on 2022-03-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0003_auto_20220314_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Deals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studenteats.Deals'),
        ),
    ]
