# Generated by Django 2.1.5 on 2022-03-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0004_auto_20220316_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Prfoile_Picture_Path',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
