# Generated by Django 2.1.5 on 2022-03-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0005_auto_20220314_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='beginnerVideo',
            field=models.URLField(default='https://google.com'),
        ),
    ]
