# Generated by Django 2.1.5 on 2022-03-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0005_auto_20220316_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_replies',
            name='Discussion_ID',
            field=models.IntegerField(default=0),
        ),
    ]
