# Generated by Django 2.1.5 on 2022-03-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0006_admindetails_beginnervideo'),
        ('studenteats', '0002_auto_20220316_1048'),
    ]

    operations = [
    ]
