# Generated by Django 2.1.5 on 2022-03-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0007_merge_20220316_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_Picture_Path',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
