# Generated by Django 2.1.5 on 2022-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0008_auto_20220316_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Created_Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
