# Generated by Django 2.1.5 on 2022-03-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0012_auto_20220317_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Deals',
            new_name='Res_Deals',
        ),
    ]
