# Generated by Django 2.1.5 on 2022-03-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenteats', '0013_auto_20220317_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_replies',
            name='Discussion_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studenteats.Discussion'),
        ),
    ]
